neo_site_settings.neo_site_settings_type.*:
  type: config_entity
  label: 'Site Settings type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
