field.field.*.*.*.third_party.neo_site_settings:
  type: mapping
  label: 'Shortcut settings'
  mapping:
    config_name:
      type: string
      label: Config Name
    config_key:
      type: string
      label: Config Key
    config_delimiter:
      type: string
      label: Config Delimiter

neo_site_settings.neo_site_settings_type.*:
  type: config_entity
  label: 'Site Settings type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: Weight
    aggregate:
      type: boolean
      label: Aggregate
    icon:
      type: string
      label: Icon

block.settings.neo_site_settings:
  type: block_settings
  label: 'Site Settings block'
  mapping:
    site_settings_type:
      type: string
      label: 'Type'
    site_settings_view_mode:
      type: string
      label: 'View Mode'

block.settings.neo_site_settings_field:
  type: block_settings
  label: 'Site Settings fields block'
  mapping:
    site_settings_fields:
      type: sequence
      label: 'Fields'
      sequence:
        type: string
    site_settings_view_mode:
      type: string
      label: 'View Mode'

neo_alchemist.neo_component_value.site_settings:
  type: mapping
  label: 'Site Settings value provider'
  mapping:
    bundle:
      type: string
      label: 'Site Settings bundle'
    shape_fields:
      type: neo_alchemist.neo_component_shape_fields
    shape_published:
      type: boolean
      label: Shape published

neo_alchemist.neo_component_value.site_settings_links:
  type: mapping
  label: 'Site Settings links value provider'
  mapping:
    bundle:
      type: string
      label: 'Site Settings bundle'

neo_alchemist.neo_component_value.site_settings_field:
  type: mapping
  label: 'Site Settings field value provider'
  mapping:
    bundle:
      type: string
      label: 'Site Settings bundle'
    field:
      type: string
      label: 'Field'
    render:
      type: boolean
      label: 'Render through field display'

neo_alchemist.neo_component_value.site_settings_fallback_media:
  type: mapping
  label: 'Site Settings fallback media value provider'
  mapping:
    bundle:
      type: string
      label: 'Site Settings bundle'
    field:
      type: string
      label: 'Media field'
